### ISSUE TITLE
Modifying news posts or changing tag list breaks Xranklin

### ISSUE THREAD

**Issue by luraess** [PTsolvers/GPU4GEO#2]
@tlienart Modifying any news `.md` file (adding/deleting a post [file]) in the Coder theme breaks Xranklin up to a point that the only workaround is currently to re-clone the repo. Executing
```
using Xranklin
serve(clear=true)
```
works in the current config (aka with the files from GitHub). However, removing any post (or news) `.md` file in the posts folder generates the following error, which remains independently of adding back more post files:
```
julia> serve(clear=true)
[ Info: ⌛ processing config.md
[ Info: ... [config.md] ✔ (δt = 6ms)
  Activating project at `~/Documents/git/github_PTsolvers/GPU4GEO`
[ Info: ⌛ processing utils.jl
[ Info:   ⏯️  evaluating cell utils...
[ Info: ... [utils.jl] ✔ (δt = 87ms)

[ Info: 💡 starting the full pass

[ Info: ⌛ processing project.md
[ Info: ... [process] ✔ (δt = 0.1s), wrote __site/project/index.html
[ Info: ⌛ processing publications.md
[ Info: ... [process] ✔ (δt = 70ms), wrote __site/publications/index.html
[ Info: ⌛ processing software.md
[ Info: ... [process] ✔ (δt = 74ms), wrote __site/software/index.html
[ Info: ⌛ processing team.md
[ Info: ... [process] ✔ (δt = 88ms), wrote __site/team/index.html
[ Info: ⌛ processing posts/emoji-support.md
[ Info:   ⏯️  evaluating cell auto_cell_1...
ERROR: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening token 'CODE_SINGLE' was found but not closed.\n")
Stacktrace:
  [1] parser_exception
    @ ~/.julia/packages/FranklinParser/nnfSV/src/utils/errors.jl:6 [inlined]
  [2] _find_blocks!(blocks::Vector{FranklinParser.Block}, tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, templates::OrderedCollections.LittleDict{Symbol, FranklinParser.BlockTemplate, Vector{Symbol}, Vector{FranklinParser.BlockTemplate}}, is_active::Vector{Bool}; process_linereturn::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:148
  [3] find_blocks(tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}; is_md::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:28
  [4] (::FranklinParser.var"#66#67")(t::Vector{FranklinParser.Token})
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:108
  [5] partition(s::SubString{String}, tokenizer::FranklinParser.var"#64#65"{OrderedCollections.LittleDict{Char, Vector{Pair{FranklinParser.TokenFinder, Symbol}}, Vector{Char}, Vector{Vector{Pair{FranklinParser.TokenFinder, Symbol}}}}}, blockifier::FranklinParser.var"#66#67"; tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, disable::Vector{Symbol}, postproc::typeof(FranklinParser.default_md_postproc!))
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:40
  [6] #md_partition#70
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [7] md_partition
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [8] convert_md(md::SubString{String}, c::Xranklin.LocalContext; tohtml::Bool, nop::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:62
  [9] convert_md(md::SubString{String}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:51
 [10] html(md::SubString{String}, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:126
 [11] html
    @ ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:126 [inlined]
 [12] #html#112
    @ ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:130 [inlined]
 [13] html
    @ ~/.julia/packages/Xranklin/0rQQN/src/convert/markdown/md_core.jl:130 [inlined]
 [14] _process_md_file_html(lc::Xranklin.LocalContext, page_content_md::String; skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:411
 [15] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:331
 [16] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:60
 [17] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, rpath::String; kw::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:initial_pass,), Tuple{Bool}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:27
 [18] getvarfrom(n::Symbol, rpath::String, d::Nothing)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/context/context.jl:395
 [19] getvarfrom
    @ ~/.julia/packages/Xranklin/0rQQN/src/context/context.jl:387 [inlined]
 [20] (::Main.__FRANKLIN_1405648.var"#6#10")(rp::String)
    @ Main.__FRANKLIN_1405648 ./none:0
 [21] iterate
    @ ./generator.jl:47 [inlined]
 [22] collect(itr::Base.Generator{Vector{String}, Main.__FRANKLIN_1405648.var"#6#10"})
    @ Base ./array.jl:724
 [23] get_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:67
 [24] hfun_list_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:50
 [25] hfun_taglist()
    @ Main.__FRANKLIN_1405648 ./string:37
 [26] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [27] invokelatest
    @ ./essentials.jl:714 [inlined]
 [28] outputof(f::Function, args::Vector{String}; tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/postprocess/utils.jl:7
 [29] html2(parts::Vector{FranklinParser.Block}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/postprocess/html2.jl:137
 [30] html2(s::String, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/convert/postprocess/html2.jl:17
 [31] html2
    @ ~/.julia/packages/Xranklin/0rQQN/src/convert/postprocess/html2.jl:17 [inlined]
 [32] (::Xranklin.var"#27#28"{Xranklin.LocalContext})(f::IOStream)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/context/tags.jl:124
 [33] open(::Xranklin.var"#27#28"{Xranklin.LocalContext}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
 [34] open
    @ ./io.jl:328 [inlined]
 [35] write_tag_page(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/context/tags.jl:123
 [36] add_tag(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String, name::String, rpath::String)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/context/tags.jl:41
 [37] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:379
 [38] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/md.jl:60
 [39] process_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpair::Pair{String, String}, case::Symbol, t::Float64; skip_files::Vector{Pair{String, String}}, initial_pass::Bool, final::Bool, reproc::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/process/process.jl:68
 [40] full_pass(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}; skip_files::Vector{Pair{String, String}}, layout_changed::Bool, config_changed::Bool, utils_changed::Bool, final::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/build/full_pass.jl:104
 [41] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, prepath::String, prefix::String, base_url_prefix::String, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/0rQQN/src/build/serve.jl:118
 [42] top-level scope
    @ REPL[2]:1

Julia>
```

Nothing helps to restaure the working behaviour after the first error occurred, the only workaround is to re-clone the repo from GitHub. Any hints on what is going wrong?

**Comment by tlienart** [comment]
Thanks for the report, I'll try to reproduce that and see what's happening; there's a bunch of pending fixes on a dev branch of xranklin and coder so I'll have to check whether the issue has already been fixed or not!

**Comment by tlienart** [comment]
The issue where you would edit the list of tags and the server would crash should be fixed now on the main branch. Could you check and report if it works for you too?

Also I'm not sure if you're referring to another issue in your post as well, if so, could you check if it's still there and if it is, re-ping me with the details? thanks!

**Comment by tlienart** [comment]
ah it's about deleting a file in `posts`; ok so this doesn't crash the server but it looks like it's causing troubles anyway because the list of blog post is not updated, I'll investigate that.

**Comment by luraess** [comment]
> The issue where you would edit the list of tags and the server would crash should be fixed now on the main branch

Modifying the tag list works now. Thanks 🙏 !

> ah it's about deleting a file in posts [...] edit: that too should be fixed, let me know!

Just tried from latest `master` and it still crashes the server to add or remove `.md` files that should show up in `posts`.

**Comment by tlienart** [comment]
Hmm I tried this and it worked, I'll have another look.

Could you post the stacktrace you got? Thanks!

**Comment by luraess** [comment]
Weird. That's the error I am getting on a fresh Julia start since I previously tried to remove one of the `.md` files from the `posts` dir.
```
julia> using Xranklin

julia> serve(clear=true)
[ Info: ⌛ processing config.md
[ Info: ... [config.md] ✔ (δt = 1.9s)
  Activating project at `~/Documents/git/github_PTsolvers/GPU4GEO`
[ Info: ⌛ processing utils.jl
[ Info:   ⏯️  evaluating cell utils...
[ Info: ... [utils.jl] ✔ (δt = 0.3s)

[ Info: 💡 starting the full pass

[ Info: ⌛ processing project.md
[ Info: ... [process] ✔ (δt = 2.9s), wrote __site/project/index.html
[ Info: ⌛ processing publications.md
[ Info: ... [process] ✔ (δt = 0.2s), wrote __site/publications/index.html
[ Info: ⌛ processing software.md
[ Info: ... [process] ✔ (δt = 39ms), wrote __site/software/index.html
[ Info: ⌛ processing team.md
[ Info: ... [process] ✔ (δt = 14ms), wrote __site/team/index.html
[ Info: ⌛ processing posts/emoji-support.md
[ Info:   ⏯️  evaluating cell auto_cell_1...
ERROR: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening token 'CODE_SINGLE' was found but not closed.\n")
Stacktrace:
  [1] parser_exception
    @ ~/.julia/packages/FranklinParser/nnfSV/src/utils/errors.jl:6 [inlined]
  [2] _find_blocks!(blocks::Vector{FranklinParser.Block}, tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, templates::OrderedCollections.LittleDict{Symbol, FranklinParser.BlockTemplate, Vector{Symbol}, Vector{FranklinParser.BlockTemplate}}, is_active::Vector{Bool}; process_linereturn::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:148
  [3] find_blocks(tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}; is_md::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:28
  [4] (::FranklinParser.var"#66#67")(t::Vector{FranklinParser.Token})
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:108
  [5] partition(s::SubString{String}, tokenizer::FranklinParser.var"#64#65"{OrderedCollections.LittleDict{Char, Vector{Pair{FranklinParser.TokenFinder, Symbol}}, Vector{Char}, Vector{Vector{Pair{FranklinParser.TokenFinder, Symbol}}}}}, blockifier::FranklinParser.var"#66#67"; tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, disable::Vector{Symbol}, postproc::typeof(FranklinParser.default_md_postproc!))
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:40
  [6] #md_partition#70
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [7] md_partition
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [8] convert_md(md::SubString{String}, c::Xranklin.LocalContext; tohtml::Bool, nop::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:62
  [9] convert_md(md::SubString{String}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:51
 [10] html(md::SubString{String}, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:126
 [11] html
    @ ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:126 [inlined]
 [12] #html#124
    @ ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:130 [inlined]
 [13] html
    @ ~/.julia/packages/Xranklin/gs4LD/src/convert/markdown/md_core.jl:130 [inlined]
 [14] _process_md_file_html(lc::Xranklin.LocalContext, page_content_md::String; skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:434
 [15] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:343
 [16] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:61
 [17] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, rpath::String; kw::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:initial_pass,), Tuple{Bool}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:27
 [18] getvarfrom(n::Symbol, rpath::String, d::Nothing)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/context/context.jl:395
 [19] getvarfrom
    @ ~/.julia/packages/Xranklin/gs4LD/src/context/context.jl:387 [inlined]
 [20] (::Main.__FRANKLIN_1405648.var"#6#10")(rp::String)
    @ Main.__FRANKLIN_1405648 ./none:0
 [21] iterate
    @ ./generator.jl:47 [inlined]
 [22] collect(itr::Base.Generator{Vector{String}, Main.__FRANKLIN_1405648.var"#6#10"})
    @ Base ./array.jl:724
 [23] get_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:67
 [24] hfun_list_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:50
 [25] hfun_taglist()
    @ Main.__FRANKLIN_1405648 ./string:37
 [26] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [27] invokelatest
    @ ./essentials.jl:714 [inlined]
 [28] outputof(f::Function, args::Vector{String}; tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/utils.jl:7
 [29] _dbb_fun(io::IOBuffer, fname::Symbol, args::Vector{String}, mdl::Module, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/dbb.jl:123
 [30] resolve_dbb(io::IOBuffer, parts::Vector{FranklinParser.Block}, idx::Int64, c::Xranklin.LocalContext, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/dbb.jl:73
 [31] html2(parts::Vector{FranklinParser.Block}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/html2.jl:65
 [32] html2(s::String, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/html2.jl:15
 [33] html2
    @ ~/.julia/packages/Xranklin/gs4LD/src/convert/postprocess/html2.jl:15 [inlined]
 [34] (::Xranklin.var"#31#32"{Xranklin.LocalContext})(f::IOStream)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/context/tags.jl:128
 [35] open(::Xranklin.var"#31#32"{Xranklin.LocalContext}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
 [36] open
    @ ./io.jl:328 [inlined]
 [37] write_tag_page(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/context/tags.jl:127
 [38] add_tag(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String, name::String, rpath::String)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/context/tags.jl:41
 [39] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:402
 [40] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/md.jl:61
 [41] process_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpair::Pair{String, String}, case::Symbol, t::Float64; skip_files::Vector{Pair{String, String}}, initial_pass::Bool, final::Bool, reproc::Bool, allow_full_skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/process/process.jl:68
 [42] full_pass(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}; skip_files::Vector{Pair{String, String}}, layout_changed::Bool, config_changed::Bool, utils_changed::Bool, allow_full_skip::Bool, final::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/build/full_pass.jl:108
 [43] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, prepath::String, prefix::String, base_url_prefix::String, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gs4LD/src/build/serve.jl:125
 [44] top-level scope
    @ REPL[2]:1

Julia>
```

**Comment by tlienart** [comment]
The error that you're reporting is likely unrelated. If you don't mind could you re-clone https://github.com/tlienart/coder-xranklin-demo ; update Xranklin, and then try to do the steps that generated the errors? 

I just tried on my side to add remove single or multiple files in `posts/` without issues, same with tags. I'd expect you will not get an error, but if you do, it shouldn't be the error above. 

Thanks!

**Comment by luraess** [comment]
Hum, must have done something wrong previously. Now it indeed works as you suggest. Thanks for the fixes ❤️ !

**Comment by luraess** [comment]
Wait. It's weird though. If I stop the server and relaunch it (even closing Julia in between), I am getting:
```
julia> using Xranklin

julia> serve(clear=true)
[ Info: ⌛ processing config.md
[ Info: ... [config.md] ✔ (δt = 1.9s)
  Activating project at `~/Documents/git/github_PTsolvers/GPU4GEO`
[ Info: ⌛ processing utils.jl
[ Info:   ⏯️  evaluating cell utils...
[ Info: ... [utils.jl] ✔ (δt = 0.3s)

[ Info: 💡 starting the full pass

[ Info: ⌛ processing project.md
[ Info: ... [process] ✔ (δt = 2.9s), wrote __site/project/index.html
[ Info: ⌛ processing publications.md
[ Info: ... [process] ✔ (δt = 0.2s), wrote __site/publications/index.html
[ Info: ⌛ processing software.md
[ Info: ... [process] ✔ (δt = 46ms), wrote __site/software/index.html
[ Info: ⌛ processing team.md
[ Info: ... [process] ✔ (δt = 13ms), wrote __site/team/index.html
[ Info: ⌛ processing posts/emoji-support.md
[ Info:   ⏯️  evaluating cell auto_cell_1...
ERROR: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening token 'CODE_SINGLE' was found but not closed.\n")
Stacktrace:
  [1] parser_exception
    @ ~/.julia/packages/FranklinParser/nnfSV/src/utils/errors.jl:6 [inlined]
  [2] _find_blocks!(blocks::Vector{FranklinParser.Block}, tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, templates::OrderedCollections.LittleDict{Symbol, FranklinParser.BlockTemplate, Vector{Symbol}, Vector{FranklinParser.BlockTemplate}}, is_active::Vector{Bool}; process_linereturn::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:148
  [3] find_blocks(tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}; is_md::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:28
  [4] (::FranklinParser.var"#66#67")(t::Vector{FranklinParser.Token})
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:108
  [5] partition(s::SubString{String}, tokenizer::FranklinParser.var"#64#65"{OrderedCollections.LittleDict{Char, Vector{Pair{FranklinParser.TokenFinder, Symbol}}, Vector{Char}, Vector{Vector{Pair{FranklinParser.TokenFinder, Symbol}}}}}, blockifier::FranklinParser.var"#66#67"; tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, disable::Vector{Symbol}, postproc::typeof(FranklinParser.default_md_postproc!))
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:40
  [6] #md_partition#70
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [7] md_partition
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [8] convert_md(md::SubString{String}, c::Xranklin.LocalContext; tohtml::Bool, nop::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:62
  [9] convert_md(md::SubString{String}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:51
 [10] html(md::SubString{String}, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:126
 [11] html
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:126 [inlined]
 [12] #html#124
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:130 [inlined]
 [13] html
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:130 [inlined]
 [14] _process_md_file_html(lc::Xranklin.LocalContext, page_content_md::String; skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:434
 [15] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:343
 [16] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:61
 [17] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, rpath::String; kw::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:initial_pass,), Tuple{Bool}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:27
 [18] getvarfrom(n::Symbol, rpath::String, d::Nothing)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/context.jl:395
 [19] getvarfrom
    @ ~/.julia/packages/Xranklin/gMSyX/src/context/context.jl:387 [inlined]
 [20] (::Main.__FRANKLIN_1405648.var"#6#10")(rp::String)
    @ Main.__FRANKLIN_1405648 ./none:0
 [21] iterate
    @ ./generator.jl:47 [inlined]
 [22] collect(itr::Base.Generator{Vector{String}, Main.__FRANKLIN_1405648.var"#6#10"})
    @ Base ./array.jl:724
 [23] get_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:67
 [24] hfun_list_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:50
 [25] hfun_taglist()
    @ Main.__FRANKLIN_1405648 ./string:37
 [26] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [27] invokelatest
    @ ./essentials.jl:714 [inlined]
 [28] outputof(f::Function, args::Vector{String}; tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/utils.jl:7
 [29] _dbb_fun(io::IOBuffer, fname::Symbol, args::Vector{String}, mdl::Module, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/dbb.jl:123
 [30] resolve_dbb(io::IOBuffer, parts::Vector{FranklinParser.Block}, idx::Int64, c::Xranklin.LocalContext, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/dbb.jl:73
 [31] html2(parts::Vector{FranklinParser.Block}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:65
 [32] html2(s::String, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:15
 [33] html2
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:15 [inlined]
 [34] (::Xranklin.var"#31#32"{Xranklin.LocalContext})(f::IOStream)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:128
 [35] open(::Xranklin.var"#31#32"{Xranklin.LocalContext}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
 [36] open
    @ ./io.jl:328 [inlined]
 [37] write_tag_page(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:127
 [38] add_tag(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String, name::String, rpath::String)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:41
 [39] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:402
 [40] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:61
 [41] process_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpair::Pair{String, String}, case::Symbol, t::Float64; skip_files::Vector{Pair{String, String}}, initial_pass::Bool, final::Bool, reproc::Bool, allow_full_skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/process.jl:68
 [42] full_pass(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}; skip_files::Vector{Pair{String, String}}, layout_changed::Bool, config_changed::Bool, utils_changed::Bool, allow_full_skip::Bool, final::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/full_pass.jl:108
 [43] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, prepath::String, prefix::String, base_url_prefix::String, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/serve.jl:125
 [44] top-level scope
    @ REPL[3]:1

julia>
```

**Comment by luraess** [comment]
No prob. Can do so. Thanks for fixing the issue at the "source" 🙂!

**Comment by tlienart** [comment]
thanks for the report, turns out there's some stuff to be careful about when deleting files (now fixed) and a re-trigger when pages are added to make sure all lists are "fresh" (also fixed).

Please keep reporting if you experience issues or pain points with any of this; there were also some changes to increase build speed out of cache (by a very significant margin) which shouldn't have broken anything (actually improved a bunch of stuff) but it's fresh out of the oven, so having someone to report issues is invaluable. Thanks!

**Comment by luraess** [comment]
Interesting, adding a new `.md` file  to `posts` folder in the Coder example works, however, deleting it fails with following error

```
[ Info: 💥 file posts/julia-hackathon-2022.md changed
[ Info: ⌛ processing posts/julia-hackathon-2022.md
[ Info: ... [process] ✔ (δt = 8ms), wrote __site/posts/julia-hackathon-2022/index.html
[ Info: ✅  Website updated and ready to view
[ Info: ❌ removed file posts/julia-hackathon-2022.md
[ Info:  → triggering full pass [page(s) added or removed]
[ Info: ⌛ processing utils.jl
[ Info:   ⏯️  evaluating cell utils...
[ Info: ... [utils.jl] ✔ (δt = 0.1s)
[ Info: ⌛ processing config.md
[ Info: ... [config.md] ✔ (δt = 5ms)

[ Info: 💡 starting the full pass

[ Info: ⌛ processing about.md
[ Info: ... [process] ✔ (δt = 9ms), wrote __site/about/index.html
[ Info: ⌛ processing contact.md
[ Info: ... [process] ✔ (δt = 5ms), wrote __site/contact/index.html
[ Info: ⌛ processing projects.md
[ Info: ... [process] ✔ (δt = 7ms), wrote __site/projects/index.html
[ Info: ⌛ processing posts/emoji-support.md
[ Info:   ⏯️  evaluating cell auto_cell_1...
ERROR: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening token 'CODE_SINGLE' was found but not closed.\n")
Stacktrace:
 [1] serve(fw::LiveServer.SimpleWatcher; host::String, port::Int64, dir::String, verbose::Bool, coreloopfun::Xranklin.var"#259#260"{OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}}, preprocess_request::typeof(identity), inject_browser_reload_script::Bool, launch_browser::Bool, allow_cors::Bool)
   @ LiveServer ~/.julia/packages/LiveServer/9wa2n/src/server.jl:456
 [2] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, prepath::String, prefix::String, base_url_prefix::String, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
   @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/serve.jl:133
 [3] top-level scope
   @ REPL[2]:1

caused by: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening token 'CODE_SINGLE' was found but not closed.\n")
Stacktrace:
  [1] parser_exception
    @ ~/.julia/packages/FranklinParser/nnfSV/src/utils/errors.jl:6 [inlined]
  [2] _find_blocks!(blocks::Vector{FranklinParser.Block}, tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, templates::OrderedCollections.LittleDict{Symbol, FranklinParser.BlockTemplate, Vector{Symbol}, Vector{FranklinParser.BlockTemplate}}, is_active::Vector{Bool}; process_linereturn::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:148
  [3] find_blocks(tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}; is_md::Bool)
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/blocks/find_blocks.jl:28
  [4] (::FranklinParser.var"#66#67")(t::Vector{FranklinParser.Token})
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:108
  [5] partition(s::SubString{String}, tokenizer::FranklinParser.var"#64#65"{OrderedCollections.LittleDict{Char, Vector{Pair{FranklinParser.TokenFinder, Symbol}}, Vector{Char}, Vector{Vector{Pair{FranklinParser.TokenFinder, Symbol}}}}}, blockifier::FranklinParser.var"#66#67"; tokens::SubArray{FranklinParser.Token, 1, Vector{FranklinParser.Token}, Tuple{UnitRange{Int64}}, true}, disable::Vector{Symbol}, postproc::typeof(FranklinParser.default_md_postproc!))
    @ FranklinParser ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:40
  [6] #md_partition#70
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [7] md_partition
    @ ~/.julia/packages/FranklinParser/nnfSV/src/partition.jl:111 [inlined]
  [8] convert_md(md::SubString{String}, c::Xranklin.LocalContext; tohtml::Bool, nop::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:62
  [9] convert_md(md::SubString{String}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:51
 [10] html(md::SubString{String}, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:126
 [11] html
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:126 [inlined]
 [12] #html#124
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:130 [inlined]
 [13] html
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/markdown/md_core.jl:130 [inlined]
 [14] _process_md_file_html(lc::Xranklin.LocalContext, page_content_md::String; skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:434
 [15] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:343
 [16] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:61
 [17] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, rpath::String; kw::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:initial_pass,), Tuple{Bool}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:27
 [18] getvarfrom(n::Symbol, rpath::String, d::Nothing)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/context.jl:395
 [19] getvarfrom
    @ ~/.julia/packages/Xranklin/gMSyX/src/context/context.jl:387 [inlined]
 [20] (::Main.__FRANKLIN_1405648.var"#6#10")(rp::String)
    @ Main.__FRANKLIN_1405648 ./none:0
 [21] iterate
    @ ./generator.jl:47 [inlined]
 [22] collect(itr::Base.Generator{Vector{String}, Main.__FRANKLIN_1405648.var"#6#10"})
    @ Base ./array.jl:724
 [23] get_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:67
 [24] hfun_list_posts(t::String)
    @ Main.__FRANKLIN_1405648 ./string:50
 [25] hfun_taglist()
    @ Main.__FRANKLIN_1405648 ./string:37
 [26] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [27] invokelatest
    @ ./essentials.jl:714 [inlined]
 [28] outputof(f::Function, args::Vector{String}; tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/utils.jl:7
 [29] _dbb_fun(io::IOBuffer, fname::Symbol, args::Vector{String}, mdl::Module, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/dbb.jl:123
 [30] resolve_dbb(io::IOBuffer, parts::Vector{FranklinParser.Block}, idx::Int64, c::Xranklin.LocalContext, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, lc::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/dbb.jl:73
 [31] html2(parts::Vector{FranklinParser.Block}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:65
 [32] html2(s::String, c::Xranklin.LocalContext; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:15
 [33] html2
    @ ~/.julia/packages/Xranklin/gMSyX/src/convert/postprocess/html2.jl:15 [inlined]
 [34] (::Xranklin.var"#31#32"{Xranklin.LocalContext})(f::IOStream)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:128
 [35] open(::Xranklin.var"#31#32"{Xranklin.LocalContext}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
 [36] open
    @ ./io.jl:328 [inlined]
 [37] write_tag_page(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:127
 [38] add_tag(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, id::String, name::String, rpath::String)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/context/tags.jl:41
 [39] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, allow_full_skip::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:402
 [40] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, allow_full_skip::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/md.jl:61
 [41] process_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpair::Pair{String, String}, case::Symbol, t::Float64; skip_files::Vector{Pair{String, String}}, initial_pass::Bool, final::Bool, reproc::Bool, allow_full_skip::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/process/process.jl:68
 [42] full_pass(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}; skip_files::Vector{Pair{String, String}}, layout_changed::Bool, config_changed::Bool, utils_changed::Bool, allow_full_skip::Bool, final::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/full_pass.jl:108
 [43] build_loop(cycle_counter::Int64, #unused#::LiveServer.SimpleWatcher, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}})
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/build_loop.jl:69
 [44] #259
    @ ~/.julia/packages/Xranklin/gMSyX/src/build/serve.jl:131 [inlined]
 [45] serve(fw::LiveServer.SimpleWatcher; host::String, port::Int64, dir::String, verbose::Bool, coreloopfun::Xranklin.var"#259#260"{OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64}}}}, preprocess_request::typeof(identity), inject_browser_reload_script::Bool, launch_browser::Bool, allow_cors::Bool)
    @ LiveServer ~/.julia/packages/LiveServer/9wa2n/src/server.jl:449
 [46] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, prepath::String, prefix::String, base_url_prefix::String, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/gMSyX/src/build/serve.jl:133
 [47] top-level scope
    @ REPL[2]:1

Julia>
```

**Comment by tlienart** [comment]
And you've done no other change to the repo? 

This is wild, the code not closed error is completely unrelated and would happen when you have an actual typo or when there's some hfun that fails.

Would you mind copy pasting the content of `Julia-hackathon`? Eg are you using backticks in the tags or something?

Thanks for helping, we'll figure this one out :-)

**Comment by luraess** [comment]
No other changes, no. But maybe as you suggests, the content of the `julia-hackathon-2022` has an issue. Here it is
```md
+++
using Dates

title = "Julia hackathon 2022"
date  = DateTime(2022, 3, 18)
reading_time = "3-minute read"

tags = ["activities", "julia", "coding"]
+++

The [GPU4GEO team](/team) and external collaborators will gather for a Julia hackathon April 4-8, 2022 to advance geoscientific Julia projects.

## Hackathon purpose

We aim at moving forward with the various open-source Julia projects within ice-flow dynamics and geodynamics where collaboration with experts enables the fast track.

During the hackathon, we will focus on advancing Julia software engineering and high-performance, parallel, GPU-accelerated code development in following topics:
- Advection, marker-based routines & combining that with [ParallelStencil.jl](https://github.com/omlins/ParallelStencil.jl)
- Developing new software using ParallelStencil (e.g., seismic rupture)
- Further develop rheology/material parameter routines ([GeoParams.jl](https://github.com/JuliaGeodynamics/GeoParams.jl)) & use that in existing codes
- Make [Enzyme.jl](https://github.com/EnzymeAD/Enzyme.jl), [Zygote.jl](https://github.com/FluxML/Zygote.jl) work with GPUs
- Explore GPU block-based dynamic tiling
- Finish DMSTAG routines within [PETSc.jl](https://github.com/JuliaParallel/PETSc.jl)
- Further develop geomIO & make [GeophysicalModelGenerator.jl](https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl) work with parallel setup
- Add higher-order derivatives to ParallelStencil.jl
- ...

Stay tuned as more news will follow
```

**Comment by tlienart** [comment]
Can you change `DateTime` for `Date`?

**Comment by luraess** [comment]
Changing to `Date` does not fix the issue. Also, the issue does not seem to be related to my new post. It looks like the server fails upon the second post `.md` file one tries to remove from the `posts` folder, independently of its content (tested adding and removing the original post files).

**Comment by tlienart** [comment]
Ok! Could I ask you to have a dummy repo will all these files that I can clone and a sequence (or sequences) of steps that I can try doing which generate an error?

You can also help investigate what's going on if you want by adding `debug=true` in the call to `serve` and telling me what appears towards the end before the crash.

Sorry about that, it's an odd one!

**Comment by luraess** [comment]
I guess I found the source of the bug @tlienart. The first time one changes (adds/removes) a file in `posts`, it creates a `.DS_Store` within the `posts` folder. Whatever next operation that would modify something in the posts folder will trigger the server to fail on the newly created `.DS_Store` (which I suspect should be hidden to the server). Removing manually the `.DS_Store` after any change solves the issue.

**Comment by tlienart** [comment]
Ok I can exactly reproduce this; there's already a path to explicitly ignore `DS_Store` file but it looks like there's something wrong going on, basically even if the `DS_Store` file is considered, it shouldn't reach `process_md_file` (because ... it's not a `.md` file 🤪 ) 

so there's definitely a bug here, will find it and fix it. Thanks!

**Comment by tlienart** [comment]
hahaha damn I found it, it's so dumb.

So the explanation is as follows:

1. the `utils/get_posts` function retrieves posts by calling `readdir("posts")` this retrieves all files in that directory inducing this damned `.DS_Store`
2. that function then calls `getvarfrom` which **for a valid target file** retrieves a page variable at that file. But given that `.DS_Store` is in the list, ... it's going to try to get a page variable from a `.DS_Store` file and that won't work of course.

Two fixes:

1. the `getvarfrom` function must be more defensive (fix about to be pushed) to not try to retrieve variables from files that aren't valid `.md` files
2.  the `get_posts` function in the utils should filter out files that are not `.md` 

I'll fix this within the next 10 minutes then get you to try the stuff again, thanks for bearing with me on this

**Comment by tlienart** [comment]
Ok both fixed, the function to use in `utils` (if you want to change that here) is

```Julia
function get_posts(t::String)
    # find all valid "posts/xxx.md" files, exclude the index which is where
    # the post-list gets placed
    paths = joinpath.(
        "posts",
        filter!(
            p -> endswith(p, ".md") && p != "index.md",
            readdir("posts")
        )
    )
    # for each of those posts, retrieve date and title, both are expected
    # to be there
    posts = [
        (
            date  = getvarfrom(:date, rp),
            title = getvarfrom(:title, rp),
            href  = "/$(splitext(rp)[1])",
            tags  = get_page_tags(rp)
        )
        for rp in paths
    ]
    sort!(posts, by = x -> x.date, rev=true)
    if !isempty(t)
        filter!(
            p -> t in values(p.tags),
            posts
        )
    end
    return posts
end

```

**Comment by luraess** [comment]
Thanks @tlienart! All works now as expected, and local displaying in Safari is also "back" ❤️

**Comment by luraess** [comment]
https://github.com/tlienart/coder-xranklin-demo/commit/fcab01a2a7697bdaf23bb8af0b7d503d5a09d704 closes #2.
